"""
add tracked

Revision ID: 2c5fab9f0068
Revises: b9aa6cdacc5
Create Date: 2015-02-07 12:26:22.295874

"""

from alembic import op
import sqlalchemy



revision = '2c5fab9f0068'
down_revision = 'b9aa6cdacc5'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'artists', sqlalchemy.Column('tracked',
                                                sqlalchemy.Boolean(),
                                                server_default=sqlalchemy.text(u'0'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'artists', 'tracked')
    ### end Alembic commands ###
