"""
Read and write a Great data repo.

A data repo is rooted at ``great.toml`` and contains:

* ``items/<kind>.toml`` — **source.** Hand-edited by the user. The
  importer never writes here. Sparse: just what someone typed.
* ``want/<kind>.toml`` — **source.** Want-to-consume queue.
* ``comparisons/*.jsonl`` — **source.** Ranking judgments.
* ``log/<year>.jsonl`` — **source.** Hand-logged diary entries.
* ``sources/<provider>.json`` — **provider caches.** Raw JSON from
  external importers (e.g. ``albumsgenerator.json`` from
  ``great import 1001albums``).
* ``derived/<kind>.toml`` — **derived.** Auto-generated catalog
  computed from the layers above (user items + provider items +
  synthesized artists for music creators). Read by ranking, render,
  and CLI display paths.

Reads always go through the derived catalog. Writes only ever touch
sources (user files via :meth:`Store.write_items`; provider caches
via the importers). The derived catalog is recompiled on the next
read after any source file changes (mtime-based staleness check).
"""

from collections.abc import Iterable
from pathlib import Path
from typing import Any, get_args
import tomllib

from pydantic import BaseModel
import tomli_w

from great.models import (
    KIND_PLURAL,
    Comparison,
    GreatConfig,
    Item,
    ItemKind,
    ListConfig,
    LogEntry,
)

CONFIG_FILE = "great.toml"
SOURCES_DIR = "sources"
DERIVED_DIR = "derived"
MUSIC_KINDS: frozenset[ItemKind] = frozenset({"album", "song"})

DERIVED_HEADER = (
    "# Auto-generated by `great`. Do not edit by hand.\n"
    "# Source of truth: items/<kind>.toml + sources/<provider>.json.\n"
    "# Regenerated on every read when any source file changes.\n"
    "\n"
)


def items_file(kind: ItemKind) -> str:
    """Repo-relative path of the user-source items TOML for ``kind``."""
    return f"items/{KIND_PLURAL[kind]}.toml"


def want_file(kind: ItemKind) -> str:
    """Repo-relative path of the want-queue TOML for ``kind``."""
    return f"want/{KIND_PLURAL[kind]}.toml"


def derived_file(kind: ItemKind) -> str:
    """Repo-relative path of the compiled catalog TOML for ``kind``."""
    return f"{DERIVED_DIR}/{KIND_PLURAL[kind]}.toml"


def _providers() -> tuple[Any, ...]:
    """
    Return importer modules that expose provider_items/log_entries.

    Imported lazily to avoid a cycle (providers can depend on
    :mod:`great.models` but not :mod:`great.store`).
    """
    from great import albumsgenerator, antennapod  # noqa: PLC0415

    return (albumsgenerator, antennapod)


class StoreError(Exception):
    """A storage error."""


class StoreNotFoundError(StoreError):
    """No ``great.toml`` was found walking up from the start path."""


class ListNotFoundError(StoreError):
    """A referenced list name is not declared in the config."""


class CorruptStoreError(StoreError):
    """An on-disk data file violates an invariant."""


class Store:
    """Read/write a Great data repo rooted at ``root``."""

    def __init__(self, root: Path):
        self.root = root
        with (root / CONFIG_FILE).open("rb") as f:
            self.config = GreatConfig.model_validate(tomllib.load(f))

    @classmethod
    def find(cls, start: Path | None = None) -> "Store":
        """Walk upward from ``start`` (or cwd) until a config is found."""
        path = (start or Path.cwd()).resolve()
        for candidate in [path, *path.parents]:
            if (candidate / CONFIG_FILE).is_file():
                return cls(candidate)
        raise StoreNotFoundError(
            f"no {CONFIG_FILE} found in {path} or any parent",
        )

    @classmethod
    def init(cls, root: Path, config: GreatConfig) -> "Store":
        """Initialize an empty data repo at ``root``."""
        root.mkdir(parents=True, exist_ok=True)
        for sub in (
            "items",
            "comparisons/want",
            "log",
            "want",
            SOURCES_DIR,
            DERIVED_DIR,
        ):
            (root / sub).mkdir(parents=True, exist_ok=True)
        with (root / CONFIG_FILE).open("wb") as f:
            tomli_w.dump(_dump(config), f)
        return cls(root)

    def write_config(self) -> None:
        """Persist ``self.config`` back to ``great.toml``."""
        with (self.root / CONFIG_FILE).open("wb") as f:
            tomli_w.dump(_dump(self.config), f)

    @property
    def sources_dir(self) -> Path:
        """Directory where provider caches (raw JSON) live."""
        return self.root / SOURCES_DIR

    def list_config(self, name: str) -> ListConfig:
        """Return the configured list with the given name."""
        for lst in self.config.lists:
            if lst.name == name:
                return lst
        raise ListNotFoundError(f"unknown list: {name!r}")

    # -- Catalog reads (always through the derived layer) ---------------

    def items(self, kind: ItemKind) -> list[Item]:
        """
        Return the compiled catalog for ``kind``.

        Combines user-source items, provider-cached items, and the
        synthesized artist items for any music ``creators`` references.
        Recompiles transparently if any source file has changed.
        """
        self._compile_if_stale()
        return self._read_items(self.root / derived_file(kind), kind)

    def all_items(self) -> list[Item]:
        """Return compiled items across kinds configured in ``great.toml``."""
        return [
            item
            for kind in sorted({lst.kind for lst in self.config.lists})
            for item in self.items(kind)
        ]

    # -- Source writes (user-only catalog edits) ------------------------

    def write_items(self, kind: ItemKind, items: list[Item]) -> None:
        """
        Replace the user-source items file for ``kind``.

        The derived catalog rebuilds on the next read; you do not need
        to call any sync/compile method yourself.
        """
        self._write_items(self.root / items_file(kind), kind, items)

    def add_item(self, item: Item) -> bool:
        """
        Append ``item`` to its kind's user-source catalog.

        Returns ``True`` if newly added, ``False`` if already present
        in the user source. Raises :exc:`StoreError` if the id is on
        the want queue — source-catalog and want queue are disjoint.
        Provider-only items don't block adds.
        """
        if any(w.id == item.id for w in self.wants(item.kind)):
            raise StoreError(
                f"{item.id!r} is already in {want_file(item.kind)}; "
                "won't add to the consumed catalog.",
            )
        source = self._source_items(item.kind)
        if any(i.id == item.id for i in source):
            return False
        source.append(item)
        self.write_items(item.kind, source)
        return True

    def _source_items(self, kind: ItemKind) -> list[Item]:
        """Items from the user-source file only (no providers, no synth)."""
        return self._read_items(self.root / items_file(kind), kind)

    # -- Want queue (user source only) ----------------------------------

    def wants(self, kind: ItemKind) -> list[Item]:
        """Return want-queue items for ``kind`` (per kind, single queue)."""
        return self._read_items(self.root / want_file(kind), kind)

    def write_wants(self, kind: ItemKind, items: list[Item]) -> None:
        """Replace the want queue for ``kind`` with ``items``."""
        self._write_items(self.root / want_file(kind), kind, items)

    def add_want(self, item: Item) -> bool:
        """
        Append ``item`` to its kind's want queue.

        Returns ``True`` if newly added. Raises :exc:`StoreError` if
        the id is already in the user-source catalog.
        """
        if any(i.id == item.id for i in self._source_items(item.kind)):
            raise StoreError(
                f"{item.id!r} is already in {items_file(item.kind)}; "
                "won't add to the want queue.",
            )
        wants = self.wants(item.kind)
        if any(w.id == item.id for w in wants):
            return False
        wants.append(item)
        self.write_wants(item.kind, wants)
        return True

    def remove_want(self, kind: ItemKind, item_id: str) -> bool:
        """Remove ``item_id`` from ``kind``'s want queue; return if removed."""
        wants = self.wants(kind)
        kept = [w for w in wants if w.id != item_id]
        if len(kept) == len(wants):
            return False
        self.write_wants(kind, kept)
        return True

    def promote_want(self, kind: ItemKind, item_id: str) -> Item | None:
        """
        Move ``item_id`` from the want queue into the user-source catalog.

        Returns the promoted item, or ``None`` if not on the want queue.
        """
        wants = self.wants(kind)
        promoted = next((w for w in wants if w.id == item_id), None)
        if promoted is None:
            return None
        source = self._source_items(kind)
        if not any(i.id == item_id for i in source):
            source.append(promoted)
            self.write_items(kind, source)
        self.write_wants(kind, [w for w in wants if w.id != item_id])
        return promoted

    # -- Comparisons (append-only) --------------------------------------

    def comparisons(self, list_name: str) -> list[Comparison]:
        """Return all favorite-ranking comparisons for ``list_name``."""
        return self._read_comparisons(self._comparisons_path(list_name))

    def append_comparison(self, list_name: str, c: Comparison) -> None:
        """Append a favorite-ranking comparison to ``list_name``'s log."""
        _append_jsonl(
            self._comparisons_path(list_name),
            c.model_dump_json(exclude_none=True),
        )

    def want_comparisons(self, kind: ItemKind) -> list[Comparison]:
        """Return all want-ranking comparisons for ``kind``."""
        return self._read_comparisons(self._want_comparisons_path(kind))

    def append_want_comparison(self, kind: ItemKind, c: Comparison) -> None:
        """Append a want-ranking comparison to ``kind``'s want log."""
        _append_jsonl(
            self._want_comparisons_path(kind),
            c.model_dump_json(exclude_none=True),
        )

    # -- Diary log (user source + provider-synthesized) -----------------

    def log(self, year: int | None = None) -> list[LogEntry]:
        """
        Return diary entries (user-typed + provider-synthesized).

        User entries from ``log/<year>.jsonl`` are unioned with any
        entries the providers synthesize from their caches; duplicates
        on ``(kind, item, ts)`` are dropped (user entries win).
        """
        entries: list[LogEntry] = []
        seen: set[tuple[ItemKind, str, Any]] = set()
        for e in self._user_log(year=year):
            entries.append(e)
            seen.add((e.kind, e.item, e.ts))
        for prov in _providers():
            for e in prov.provider_log_entries(self.sources_dir):
                if year is not None and e.ts.year != year:
                    continue
                key = (e.kind, e.item, e.ts)
                if key in seen:
                    continue
                seen.add(key)
                entries.append(e)
        return entries

    def append_log(self, entry: LogEntry) -> None:
        """Append a user diary entry to the log for its year."""
        path = self.root / "log" / f"{entry.ts.year}.jsonl"
        _append_jsonl(path, entry.model_dump_json(exclude_none=True))

    def _user_log(self, year: int | None = None) -> list[LogEntry]:
        log_dir = self.root / "log"
        if not log_dir.is_dir():
            return []
        files = sorted(log_dir.glob("*.jsonl"))
        if year is not None:
            files = [f for f in files if f.stem == str(year)]
        return [
            LogEntry.model_validate_json(line)
            for path in files
            for line in _read_jsonl(path)
        ]

    # -- Compile (source + providers -> derived) ------------------------

    def compile(self) -> None:
        """Force a rebuild of the derived catalog. Normally invoked lazily."""
        kinds = get_args(ItemKind)
        by_kind: dict[ItemKind, dict[str, Item]] = {k: {} for k in kinds}

        # Layer 1: user source (wins on id conflict).
        for kind in kinds:
            for item in self._source_items(kind):
                by_kind[kind][item.id] = item

        # Layer 2: provider items (only fill gaps; user source wins).
        for prov in _providers():
            for item in prov.provider_items(self.sources_dir):
                if item.id not in by_kind[item.kind]:
                    by_kind[item.kind][item.id] = item

        # Layer 3: synthesize artist items for music creators that
        # don't already match an existing artist's id or title.
        existing_artist_ids = {i.id for i in by_kind["artist"].values()}
        existing_artist_titles = {i.title for i in by_kind["artist"].values()}
        synthesized: set[str] = set()
        for kind in MUSIC_KINDS:
            for item in by_kind[kind].values():
                for name in item.creators:
                    n = name.strip() if name else ""
                    if not n:
                        continue
                    if n in existing_artist_ids or n in existing_artist_titles:
                        continue
                    synthesized.add(n)
        for name in sorted(synthesized):
            by_kind["artist"][name] = Item(
                id=name,
                kind="artist",
                title=name,
            )

        derived_dir = self.root / DERIVED_DIR
        derived_dir.mkdir(parents=True, exist_ok=True)
        for kind in kinds:
            self._write_items(
                self.root / derived_file(kind),
                kind,
                list(by_kind[kind].values()),
                header=DERIVED_HEADER,
            )

    def _compile_if_stale(self) -> None:
        if self._is_derived_stale():
            self.compile()

    def _is_derived_stale(self) -> bool:
        derived_dir = self.root / DERIVED_DIR
        if not derived_dir.is_dir():
            return True
        # Use the OLDEST derived file as the freshness baseline; if any
        # source is newer than that, the catalog needs to rebuild.
        derived_files = list(derived_dir.glob("*.toml"))
        if not derived_files:
            return True
        baseline = min(f.stat().st_mtime for f in derived_files)
        for source in self._source_paths():
            if source.exists() and source.stat().st_mtime > baseline:
                return True
        return False

    def _source_paths(self) -> Iterable[Path]:
        for kind in get_args(ItemKind):
            yield self.root / items_file(kind)
        if self.sources_dir.is_dir():
            yield from self.sources_dir.glob("*.json")

    # -- File helpers ---------------------------------------------------

    def _comparisons_path(self, list_name: str) -> Path:
        return self.root / "comparisons" / f"{list_name}.jsonl"

    def _want_comparisons_path(self, kind: ItemKind) -> Path:
        return (
            self.root / "comparisons" / "want" / f"{KIND_PLURAL[kind]}.jsonl"
        )

    def _read_items(self, path: Path, kind: ItemKind) -> list[Item]:
        if not path.is_file():
            return []
        with path.open("rb") as f:
            data = tomllib.load(f)
        items: list[Item] = []
        seen: set[str] = set()
        for raw in data.get("items", []):
            try:
                item = Item.from_dict(raw, kind=kind)
            except ValueError as e:
                raise CorruptStoreError(f"{path}: {e}") from e
            if item.id in seen:
                raise CorruptStoreError(
                    f"{path}: duplicate item id {item.id!r}",
                )
            seen.add(item.id)
            items.append(item)
        return items

    def _write_items(
        self,
        path: Path,
        kind: ItemKind,
        items: list[Item],
        *,
        header: str = "",
    ) -> None:
        for item in items:
            if item.kind != kind:
                raise ValueError(
                    f"item {item.id!r} has kind {item.kind!r}, "
                    f"cannot write to {path}",
                )
        if not items:
            path.unlink(missing_ok=True)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {"items": [i.to_dict() for i in items]}
        with path.open("wb") as f:
            if header:
                f.write(header.encode())
            tomli_w.dump(payload, f)

    def _read_comparisons(self, path: Path) -> list[Comparison]:
        return [
            Comparison.model_validate_json(line) for line in _read_jsonl(path)
        ]


def _dump(model: BaseModel) -> dict[str, Any]:
    """Dump a pydantic model to a TOML-friendly dict."""
    return model.model_dump(
        mode="python",
        exclude_defaults=True,
        exclude_none=True,
    )


def _read_jsonl(path: Path) -> list[str]:
    """Return the non-empty lines of a JSONL file (or [] if missing)."""
    if not path.is_file():
        return []
    with path.open() as f:
        return [line for line in f if line.strip()]


def _append_jsonl(path: Path, line: str) -> None:
    """Append a single JSON line to ``path``, creating parents as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as f:
        f.write(line + "\n")
